/**
 * Bindings available to the worker.
 *
 * The binding shapes come from `worker-configuration.d.ts`, generated by
 * `pnpm cf-typegen` (`wrangler types`) out of wrangler.toml, so a typo or a
 * removed binding becomes a type error instead of a runtime surprise.
 *
 * `ENVIRONMENT` is widened deliberately: wrangler.toml only describes the
 * development value, while the deployed worker sets "production", and the code
 * must be able to branch on both.
 */
export type Env = Omit<Cloudflare.Env, "ENVIRONMENT"> & {
  ENVIRONMENT: "development" | "production";
};

export interface Variables {
  requestId: string;
}

/** Hono generic used by every handler and middleware in this worker. */
export interface AppBindings {
  Bindings: Env;
  Variables: Variables;
}
