import {
  MAX_ATTACHMENT_BYTES,
  base64ToBytes,
  encryptObject,
  utf8,
  type Bytes,
} from "@securenotes/shared";

import { ApiError } from "../api/client";
import { attachmentMarkdown } from "../editor/attachments";

/**
 * Uploading an attachment (§7, §12, §15).
 *
 * The bytes are encrypted **here**, before they leave the browser, exactly as a note is:
 * AES-256-GCM under the DEK with a fresh 96-bit IV, and an AAD that binds the ciphertext
 * to this attachment and its key version. The worker stores an opaque object and never
 * sees plaintext.
 *
 * The envelope travels in the `metadata` part — the object type is `attachment_blob`,
 * which the frozen format already names for exactly this purpose. Without it the upload
 * would be unreadable, which is why the API requires it.
 */

export interface UploadedAttachment {
  id: string;
  markdown: string;
}

export interface AttachmentUploadInput {
  file: File;
  /** The DEK, non-extractable. */
  dek: CryptoKey;
  keyVersion: number;
  /** Generated by the caller so the reference can be inserted before the upload lands. */
  attachmentId: string;
  headers?: Record<string, string>;
}

/** Encrypts attachment bytes and reports the envelope the API needs. */
export async function encryptAttachmentBytes(
  dek: CryptoKey,
  attachmentId: string,
  keyVersion: number,
  bytes: Bytes,
): Promise<{ ciphertext: Bytes; iv: string; plaintextSize: number }> {
  const envelope = await encryptObject(
    dek,
    {
      objectType: "attachment_blob",
      objectId: attachmentId,
      // Attachments are immutable: replacing one creates a new id, so there is no
      // revision to bind and the value is fixed.
      revision: 1,
      keyVersion,
    },
    bytes,
  );

  return {
    ciphertext: base64ToBytes(envelope.ciphertext),
    iv: envelope.iv,
    plaintextSize: bytes.byteLength,
  };
}

export async function uploadAttachment(input: AttachmentUploadInput): Promise<UploadedAttachment> {
  const { file, dek, keyVersion, attachmentId } = input;

  // `Bytes` is the WebCrypto-compatible view the shared crypto helpers require.
  const bytes = new Uint8Array(await file.arrayBuffer()) as Bytes;
  if (bytes.byteLength === 0) {
    throw new Error("The file is empty.");
  }
  if (bytes.byteLength > MAX_ATTACHMENT_BYTES) {
    throw new Error(
      `Each file must be under ${Math.round(MAX_ATTACHMENT_BYTES / (1024 * 1024))} MB.`,
    );
  }

  const { ciphertext, iv, plaintextSize } = await encryptAttachmentBytes(
    dek,
    attachmentId,
    keyVersion,
    bytes,
  );

  const metadata = {
    id: attachmentId,
    name: file.name || "attachment",
    contentType: file.type || "application/octet-stream",
    // The size the server stores and counts against the ceiling is the ciphertext.
    sizeBytes: ciphertext.byteLength,
    contentIv: iv,
    plaintextSizeBytes: plaintextSize,
  };

  const form = new FormData();
  form.set("metadata", JSON.stringify(metadata));
  form.set(
    "blob",
    new File([ciphertext as BlobPart], "blob", { type: "application/octet-stream" }),
  );

  const response = await fetch("/api/v1/attachments", {
    method: "POST",
    body: form,
    headers: input.headers,
    credentials: "same-origin",
  });

  const payload = (await response.json().catch(() => null)) as
    | { ok: true; data: { attachment: { id: string } } }
    | { ok: false; error: { code: string } }
    | null;

  if (response.status === 413) {
    throw new Error(
      `Each file must be under ${Math.round(MAX_ATTACHMENT_BYTES / (1024 * 1024))} MB.`,
    );
  }
  if (!response.ok || !payload || payload.ok !== true) {
    const code = payload && payload.ok === false ? payload.error.code : "INTERNAL";
    throw new ApiError(
      code === "PAYLOAD_TOO_LARGE" ? "PAYLOAD_TOO_LARGE" : "INTERNAL",
      response.status,
    );
  }

  return {
    id: payload.data.attachment.id,
    markdown: attachmentMarkdown(payload.data.attachment.id, file.name),
  };
}

/**
 * An attachment's alt text never carries note content: it is the filename the user
 * chose, and nothing else about the note leaks into a value a reader of the DOM can see.
 */
export const ATTACHMENT_ALT_SOURCE = utf8("attachment");
